// Kelvin-inspired: hot (colorA) → cool (colorB); pool light falls from above on grey bg
export const VOICE_STATES = {
  idle: {
    label: 'Idle',
    status: 'Ready',
    hint: 'Warm ivory luminance — calm and present',
    glow: '#f0dcc8',
    glowOpacity: 0.44,
    colorA: '#fff4e4',
    colorB: '#c88848',
    rim: '#fff0d8',
    light: '#f5e6d4',
    lightIntensity: 1.45,
    edgeGlow: 0.34,
    bodyDim: 0.78,
    bloom: 0.14,
    bloomThreshold: 0.62,
    sparks: false,
    glitch: false,
    breathe: 0.012,
    speed: 0.3,
    rotY: 0.22
  },
  listening: {
    label: 'Listening',
    status: 'Listening',
    hint: 'Cool daylight attentiveness',
    glow: '#78c0f0',
    glowOpacity: 0.46,
    colorA: '#e8f8ff',
    colorB: '#1870b8',
    rim: '#c8ecff',
    light: '#88c8f5',
    lightIntensity: 1.75,
    edgeGlow: 0.42,
    bodyDim: 0.66,
    bloom: 0.18,
    bloomThreshold: 0.74,
    sparks: false,
    glitch: false,
    breathe: 0.028,
    speed: 0.65,
    rotY: 0.22
  },
  thinking: {
    label: 'Thinking',
    status: 'Thinking',
    hint: 'Soft violet drift while processing',
    glow: '#a898e8',
    glowOpacity: 0.4,
    colorA: '#f0ecff',
    colorB: '#5848b8',
    rim: '#d8d0ff',
    light: '#b8a8e8',
    lightIntensity: 1.55,
    edgeGlow: 0.38,
    bodyDim: 0.66,
    bloom: 0.16,
    bloomThreshold: 0.76,
    sparks: false,
    glitch: false,
    breathe: 0.018,
    speed: 0.9,
    rotY: 0.22,
    wobble: 0.04
  },
  speaking: {
    label: 'Speaking',
    status: 'Speaking',
    hint: 'Peak energy — cool blue light & soft sparks',
    glow: '#50ebff',
    glowOpacity: 0.74,
    colorA: '#f0fcff',
    colorB: '#22c8ff',
    rim: '#e8fcff',
    light: '#60e8ff',
    lightIntensity: 2.35,
    edgeGlow: 0.68,
    bodyDim: 0.76,
    bloom: 1.85,
    bloomThreshold: 0.24,
    sparks: true,
    glitch: false,
    breathe: 0.085,
    speed: 0.9,
    rotY: 0.22
  },
  interrupted: {
    label: 'Interrupted',
    status: 'Interrupted',
    hint: 'Warm amber alert — conversation cut short',
    glow: '#ff6020',
    glowOpacity: 0.68,
    colorA: '#fff0d8',
    colorB: '#c83008',
    rim: '#ffb070',
    light: '#ff7830',
    lightIntensity: 2.0,
    edgeGlow: 0.64,
    bodyDim: 0.63,
    bloom: 0.28,
    bloomThreshold: 0.68,
    sparks: false,
    glitch: false,
    breathe: 0.065,
    speed: 2.4,
    rotY: 0.22,
    flash: true
  }
}

export const STATE_ORDER = ['idle', 'listening', 'thinking', 'speaking', 'interrupted']
